vim.cmd('nmap <leader>w :w<cr>')
vim.cmd('nmap <leader>q :q<cr>')
vim.keymap.set('v', '>', '>gv')
vim.keymap.set('v', '<', '<gv')
vim.keymap.set('n', '<leader>j', ':bnext<CR>', { desc = "Next buffer" })
vim.keymap.set('n', '<leader>k', ':bprevious<CR>', { desc = "Previous buffer" })
vim.keymap.set('n', '<leader>c', ':bd<CR>', { desc = "Close buffer" })
vim.keymap.set('n', '<leader>a', ':%bd<CR>', { desc = "Close all buffers" })
