vim.cmd("nmap <leader>w :w<cr>")
vim.cmd("nmap <leader>Q :q<cr>")
vim.keymap.set("n", "<leader>q", ":bd<CR>", { desc = "Close buffer" })
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("n", "<leader>j", ":bprevious<CR>", { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>k", ":bnext<CR>", { desc = "Next buffer" })
vim.keymap.set("n", "<leader>p", "<C-^>", { desc = "Switch to last buffer" })
vim.keymap.set("n", "<leader>a", ":%bd<CR>", { desc = "Close all buffers" })
vim.keymap.set("n", "<leader>v", function()
	vim.cmd("vsplit")
	vim.cmd("wincmd l")
end)
vim.keymap.set("n", "<leader>h", "<C-w>h")
vim.keymap.set("n", "<leader>l", "<C-w>l")
vim.keymap.set("n", "gd", vim.lsp.buf.definition, { silent = true })
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, { silent = true })
local function open_float_focus()
	vim.diagnostic.open_float(nil, { scope = "line" })
	vim.diagnostic.open_float(nil, { scope = "line", focus = true })
end
vim.keymap.set("n", "df", open_float_focus, { silent = true })
vim.keymap.set("n", "<M-=>", ":vertical resize +10<CR>")
vim.keymap.set("n", "<M-->", ":vertical resize -10<CR>")
